{ config, pkgs, ... }:

{
  programs.kitty = {
    enable = true;
    settings = {
      shell = "${pkgs.zsh}/bin/zsh";
      include = "main.conf";
    };
  };

  # kitty.conf is generated by `programs.kitty` above - use main.conf,
  # which is included by the generated kitty.conf.
  home.file.".config/kitty/main.conf".source = ./config/kitty/main.conf;
  # colorsmatugen.conf is modified by Mutagen, so it has to be writable
  home.file.".config/kitty/colors-matugen.conf".source =
    config.lib.file.mkOutOfStoreSymlink
    "${config.home.homeDirectory}/.dotfiles/config/home-manager/modules/wm/config/kitty/colors-matugen.conf";
}
