$image = /home/jogravel/.config/wallpapers/fall-echo-tries.png

$background = rgba(18130bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(362f27ff)

$inverse_primary = rgba(7e5700ff)

$inverse_surface = rgba(ece1d3ff)

$on_background = rgba(ece1d3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(432c00ff)

$on_primary_container = rgba(322000ff)

$on_primary_fixed = rgba(281900ff)

$on_primary_fixed_variant = rgba(604100ff)

$on_secondary = rgba(422c03ff)

$on_secondary_container = rgba(ffdba4ff)

$on_secondary_fixed = rgba(281900ff)

$on_secondary_fixed_variant = rgba(5b4317ff)

$on_surface = rgba(ece1d3ff)

$on_surface_variant = rgba(d5c4afff)

$on_tertiary = rgba(003256ff)

$on_tertiary_container = rgba(002541ff)

$on_tertiary_fixed = rgba(001d35ff)

$on_tertiary_fixed_variant = rgba(00497aff)

$outline = rgba(9d8f7bff)

$outline_variant = rgba(504535ff)

$primary = rgba(ffbe4aff)

$primary_container = rgba(e1a32cff)

$primary_fixed = rgba(ffdeacff)

$primary_fixed_dim = rgba(fcbb43ff)

$scrim = rgba(000000ff)

$secondary = rgba(e5c18aff)

$secondary_container = rgba(5b4317ff)

$secondary_fixed = rgba(ffdeacff)

$secondary_fixed_dim = rgba(e5c18aff)

$shadow = rgba(000000ff)

$source_color = rgba(e1a32cff)

$surface = rgba(18130bff)

$surface_bright = rgba(3f382fff)

$surface_container = rgba(241f17ff)

$surface_container_high = rgba(2f2920ff)

$surface_container_highest = rgba(3a342bff)

$surface_container_low = rgba(201b13ff)

$surface_container_lowest = rgba(120d07ff)

$surface_dim = rgba(18130bff)

$surface_tint = rgba(fcbb43ff)

$surface_variant = rgba(504535ff)

$tertiary = rgba(a1cdffff)

$tertiary_container = rgba(69b3fcff)

$tertiary_fixed = rgba(d0e4ffff)

$tertiary_fixed_dim = rgba(9ccaffff)

