general {
  inhibit_sleep=3
  after_sleep_cmd=hyprctl dispatch dpms on
  before_sleep_cmd=hyprlock --no-fade-in
  lock_cmd=pidof hyprlock || hyprlock
}

listener {
  on-resume=brightnessctl -rd rgb:kbd_backlight
  on-timeout=brightnessctl -sd rgb:kbd_backlight set 0
  timeout=240 # 4 minutes
}

listener {
  on-resume=brightnessctl -r
  on-timeout=brightnessctl -s set 10
  timeout=240 # 4 minutes
}

listener {
  on-timeout=loginctl lock-session
  timeout=360 # 6 minutes
}

listener {
  on-resume=hyprctl dispatch dpms on && brightnessctl -r
  on-timeout=hyprctl dispatch dpms off
  timeout=480 # 8 minutes
}

listener {
  on-timeout=sh -c 'if cat /sys/class/power_supply/BAT*/status 2>/dev/null | grep -q "Discharging"; then systemctl suspend; fi'
  timeout=1800 # 30 minutes
}
