# Start Waybar
exec-once = waybar

# Start Hypridle
exec-once = hypridle

# Set wallpaper
exec-once = hyprpaper

# Autostart apps
exec-once = kitty
exec-once = google-chrome
exec-once = obsidian
exec-once = /opt/Webex/bin/CiscoCollabHost
exec-once = spotify
