# -----------------------------------------------------
# Monitor Setup
# https://wiki.hypr.land/Configuring/Monitors/
# -----------------------------------------------------

# note: position must account for scale
monitor = eDP-1, 1920x1200, 0x0, 1.2
monitor = desc:Samsung Electric Company Odyssey G8 HCNWA02383, 3840x2160, 1600x-750, 1.25
monitor = desc:ViewSonic Corporation VX2778 Series ULY190760145, 2560x1440, 1600x-750, 1.07

# -----------------------------------------------------
# Laptop Switches
# https://wiki.hypr.land/Configuring/Binds/#Switches
# -----------------------------------------------------

bindl = , switch:on:Lid Switch, exec, ~/.config/hypr/scripts/clamshell.sh close
bindl = , switch:off:Lid Switch, exec, ~/.config/hypr/scripts/clamshell.sh open "eDP-1, 1920x1200, 0x0, 1.2"
