# -----------------------------------------------------
# Programs
# -----------------------------------------------------
$browser = firefox
$fileManager = nautilus
$menu = wofi --show drun -i
$terminal = kitty
