# -----------------------------------------------------
# Programs
# -----------------------------------------------------
$browser = /opt/zen/zen
$fileManager = nautilus
$menu = wofi --show drun -i
$terminal = kitty
