# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# Pavucontrol floating
windowrule = float on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = size 700 600, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = center on, match:class (.*org.pulseaudio.pavucontrol.*)
windowrule = pin on, match:class (.*org.pulseaudio.pavucontrol.*)

# Waypaper
windowrule = float on, match:class (.*waypaper.*)
windowrule = size 900 700, match:class (.*waypaper.*)
windowrule = center on, match:class (.*waypaper.*)
windowrule = pin on, match:class (.*waypaper.*)

# Blueman Manager
windowrule = float on, match:class (.*blueman-manager.*)
windowrule = size 800 600, match:class (.*blueman-manager.*)
windowrule = center on, match:class (.*blueman-manager.*)

# General floating
windowrule = float on, match:class (dotfiles-floating)
windowrule = size 1000 700, match:class (dotfiles-floating)
windowrule = center on, match:class (dotfiles-floating)

# Float and center file pickers
windowrule = float on, match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center on, match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)

# Assign common apps to specific workspaces
windowrule = workspace 1, match:class (kitty)
windowrule = workspace 2, match:class (.*firefox.*)
windowrule = workspace 2, match:class (.*google-chrome.*)
windowrule = workspace 3, match:class (.*obsidian.*)
windowrule = workspace 5, match:class (.*spotify.*)
windowrule = workspace special:im, match:class (.*webex.*)
windowrule = workspace special:mail, match:initial_title (.*Outlook.*)
